project_id = "lhamshhjmmruybdcfivr"

[functions.ai-chat-assistant]
verify_jwt = true

[functions.test-connection]
verify_jwt = false

[functions.medicine-lookup]
verify_jwt = false

[functions.text-to-speech]
verify_jwt = true

[functions.speech-to-text]
verify_jwt = true

[functions.search]
verify_jwt = false

[functions.send-email]
verify_jwt = false

[functions.appointment-reminders]
verify_jwt = false

[functions.search-providers]
verify_jwt = false

[functions.drug-interaction-checker]
verify_jwt = false

[functions.analyze-medical]
verify_jwt = false
